[package]
name = "befunk93"
version = "0.1.0"
edition = "2024"

[dependencies]
ahash = "0.8.12"
clap = { version = "4.5.42", features = ["derive"] }
crossterm = "0.29.0"
rand = "0.9.2"
ratatui = "0.29.0"
